server:
  port: 3000
  
# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(yExFK2Ed75CZ+D4Ff2MGvA==)
    url: jdbc:mysql://127.0.0.1:3307/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      
pig:
  auth:
    clientId: ENC(yExFK2Ed75CZ+D4Ff2MGvA==)
    clientSecret: ENC(yExFK2Ed75CZ+D4Ff2MGvA==)
    scope: server
  social:
    qq:
      providerId: qq
      clientId: ENC(yExFK2Ed75CZ+D4Ff2MGvA==)
      clientSecret: ENC(yExFK2Ed75CZ+D4Ff2MGvA==)

urls:
  anon:
    - /health
    - /social
    - /signin
    - /signup
    - /mobile/token

logging:
  config: classpath:logback.xml

