server:
  port: 9999

spring:
  rabbitmq:
    host: 192.168.0.147
    port: 5672
    username: qgf
    password: ENC(ZIosRGofTz0cUkkNlTsunA==)
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    pig-auth:
      path: /auth/**
      serviceId: pig-auth
      stripPrefix: true
      sensitiveHeaders:
    pig-admin-service:
      path: /admin/**
      serviceId: pig-upms-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: pig-ratelimite 
    enabled: true 
    repository: REDIS 
    behind-proxy: true
    policies:
      pig-admin-service:
        limit: 100
        quota: 100
        refresh-interval: 3

security:
  validate:
    code: false
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://pig-auth/user
      prefer-token-info: false
      service-id: pig-gateway

urls:
  anon:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
       
logging:
  config: classpath:logback.xml
