server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(yExFK2Ed75CZ+D4Ff2MGvA==)
    url: jdbc:mysql://127.0.0.1:3307/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.0.147:5672
      password: qgf
      username: qgf
      queue: zipkin
  storage:
    type: mysql